In [1]:
import pandas as pd
import datetime
from datetime import date, timedelta
from datetime import datetime
import webbrowser
import psutil
from selenium import webdriver
import os
import shutil
import subprocess
import nbformat
from nbconvert import PythonExporter
import joblib
import openpyxl
import win32com.client
import numpy as np
import collections
import re

In [2]:
from_Date = '2023-08-01'
to_Date = '2023-08-31'

In [3]:
def convert_datetime(a):
    if pd.isnull(a):
        return pd.NaT
    
    date_formats = ["%Y-%m-%d %H:%M:%S.%f", 
                    "%Y-%m-%d %H:%M:%S", 
                    "%m/%d/%Y %H:%M",
                    "%m-%d-%Y %H:%M", 
                    "%m/%d/%Y", 
                    "%Y-%m-%d", 
                    "%H:%M.%f",
                    "%m/%d/%Y %H:%M:%S"] 
    for fmt in date_formats:
        try:
            return datetime.strptime(str(a), fmt).strftime("%Y-%m-%d" )
        except ValueError:
            pass
    try:
        return (datetime(1899, 12, 30) + timedelta(days=float(a))).strftime("%Y-%m-%d")
    except ValueError:
        pass
    if not re.match("\d+:\d+:\d+(\.\d+)?", str(a)):
        return str(a)

def convert_time(a):
    if pd.isnull(a):
        return pd.NaT
    
    date_formats = ["%Y-%m-%d %H:%M:%S.%f", 
                    "%Y-%m-%d %H:%M:%S", 
                    "%m/%d/%Y %H:%M",
                    "%m-%d-%Y %H:%M", 
                    "%m/%d/%Y", 
                    "%Y-%m-%d", 
                    "%H:%M.%f",
                    "%m/%d/%Y %H:%M:%S"] 
    for fmt in date_formats:
        try:
            return datetime.strptime(str(a), fmt).strftime("%Y-%m-%d %H:%M:%S")
        except ValueError:
            pass
    try:
        return (datetime(1899, 12, 30) + timedelta(days=float(a))).strftime("%Y-%m-%d %H:%M:%S")
    except ValueError:
        pass
    if not re.match("\d+:\d+:\d+(\.\d+)?", str(a)):
        return str(a)

In [4]:
# import datetime

# folder_path = 'D:/Shrinkage/MOD Interval (hour)/csv'
# output_directory = "D:/Shrinkage/MOD Interval (hour)/xlsx"

# for filename in os.listdir(folder_path):
#     if filename.endswith('.csv'):
#         file_path = os.path.join(folder_path, filename)
        
#         df = pd.read_csv(file_path,header=None)
#         print(filename)
#         date_value = df.iloc[0, 1]
#         date_value = datetime.datetime.strptime(date_value, "%d-%b")
#         date_value = date_value.replace(year=2023)
        
#         df = df.iloc[10:]
        
#         df = df.iloc[:, :37]
        
#         column_names = ['Ecode', 'Name', 'Email', 'Role', 'LOB', 'Line Manager', 'DEnd', 'S', 'E', 'L', 'Task', 'Shift', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '0', '1', '2', '3', '4', '5', '6_1']
#         df.columns = column_names

#         df.insert(0, 'Date', date_value)

#         new_filename = os.path.splitext(filename)[0] + '.xlsx'
#         new_file_path = os.path.join(output_directory, new_filename)
        
#         df.to_excel(new_file_path, index=False)

# from datetime import datetime

In [5]:
# def rename_csv_files(folder_path, title_column, date_column, sheet_name=None):
#     files = os.listdir(folder_path)
    
#     for file in files:
#          if file.endswith(".csv") and "Working Hourly" not in file and "Working Shift" not in file:
#             file_path = os.path.join(folder_path, file)
#             print(file)
#             if sheet_name is None:
#                 df = pd.read_csv(file_path)
#             else:
#                 df = pd.read_csv(file_path, sheet_name=sheet_name)
#             try:    
#                 title = title_column
                
#                 df[date_column] = pd.to_datetime(df[date_column])
                
#                 start_date = df[date_column].min()
#                 end_date = df[date_column].max()
                                
#                 start_date_str = start_date.strftime("%Y-%m-%d")
#                 end_date_str = end_date.strftime("%Y-%m-%d")
                
#                 new_file_name = f"{title}_{start_date_str}_{end_date_str}.csv"
#                 new_file_path = os.path.join(folder_path, new_file_name)
                
#                 if os.path.exists(new_file_path):
#                     os.remove(new_file_path)
#                 os.rename(file_path, new_file_path)
#             except: pass

# dir_volume_hourly = 'D:/Shrinkage/Volume Hourly'
# dir_working_shift = 'D:/Shrinkage/Working Shift'

# rename_csv_files(dir_volume_hourly, 'Working Hourly', 'Date')
# rename_csv_files(dir_working_shift, 'Working Shift', '日期/Date')

In [6]:
# def rename_xlsx_files(folder_path, title_column, date_column, sheet_name=None):
#     files = os.listdir(folder_path)
    
#     for file in files:
#          if file.endswith(".xlsx") and "_2023" not in file:
#             file_path = os.path.join(folder_path, file)
#             print(file)
#             if sheet_name is None:
#                 df = pd.read_excel(file_path)
#             else:
#                 df = pd.read_excel(file_path, sheet_name=sheet_name)
#             try:    
#                 title = title_column
                
#                 df[date_column] = pd.to_datetime(df[date_column])
                
#                 start_date = df[date_column].min()
                                
#                 start_date_str = start_date.strftime("%Y-%m-%d")
                
#                 new_file_name = f"{title}_{start_date_str}.xlsx"
#                 new_file_path = os.path.join(folder_path, new_file_name)
                
#                 if os.path.exists(new_file_path):
#                     os.remove(new_file_path)
#                 os.rename(file_path, new_file_path)
#             except: pass

# dir_interval = 'D:/Shrinkage/MOD Interval (hour)/xlsx'
# rename_xlsx_files(dir_interval, 'MOD - Interval schedule (hour)', 'Date')

In [7]:
def merge_csv_files(folder_path):
    file_paths = [os.path.join(folder_path, file) for file in os.listdir(folder_path) if file.endswith('.csv')]

    dfs = []
    for file_path in file_paths:
        try:
            df = pd.read_csv(file_path)
            df['source_file'] = os.path.basename(file_path)

            dfs.append(df)
        except Exception as e:
            print(f"Error reading file {file_path}: {str(e)}")
  
    merged_df = pd.concat(dfs, axis=0, ignore_index=True)

    return merged_df

In [8]:
def concat_files(folder_path):
    files = [file for file in os.listdir(folder_path) if file.endswith('.xlsx')]
    
    if len(files) == 0:
        print("Thư mục không chứa file xlsx.")
        return None
    
    first_file_path = os.path.join(folder_path, files[0])
    df_header = pd.read_excel(first_file_path, header=0)
    
    num_columns = df_header.shape[1]
    
    dfs = []
    for file in files[1:]:
        file_path = os.path.join(folder_path, file)
        df = pd.read_excel(file_path, header=0)
        if df.shape[1] == num_columns:
            dfs.append(df)
    df_combined = pd.concat([df_header] + dfs)
    
    return df_combined

mod_interval_hour_raw = concat_files('D:/Shrinkage/MOD Interval (hour)/xlsx')

In [9]:
mod_interval_hour_raw =  mod_interval_hour_raw[['Date', 'Ecode', 'Name', 'Email', 'Role', 'Shift', '6', '7', '8', '9', '10', '11', '12','13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '0','1', '2', '3', '4', '5', '6_1']]
mod_interval_hour_raw = mod_interval_hour_raw[~mod_interval_hour_raw['Shift'].isin(['X','x','LongLeave','P','P4','P5','P6','P7','R',np.nan])]
mod_interval_hour = pd.melt(mod_interval_hour_raw, id_vars=['Date','Ecode', 'Name', 'Email', 'Role', 'Shift'], var_name='Slot', value_name='Values')
mask = mod_interval_hour['Slot'].isin(['6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23'])
mod_interval_hour.loc[mask, 'Date'] = mod_interval_hour.loc[mask, 'Date']
mask = mod_interval_hour['Slot'].isin(['0', '1', '2', '3', '4', '5', '6_1'])
mod_interval_hour.loc[mask, 'Date'] = mod_interval_hour.loc[mask, 'Date'] + pd.DateOffset(days=1)
mod_interval_hour['Slot'] = pd.to_datetime(mod_interval_hour['Slot'], format='%H', errors='coerce')
mod_interval_hour['Slot'] = mod_interval_hour['Slot'].dt.strftime('%H:%M')
print(mod_interval_hour['Shift'].unique())
mod_interval_hour = mod_interval_hour[(mod_interval_hour['Date'].dt.strftime('%Y-%m-%d') >= from_Date) & (mod_interval_hour['Date'].dt.strftime('%Y-%m-%d') <= to_Date)]
mod_interval_hour

['OFF' 'S09' 'S17' 'S03' 'S31' 'S33' 'S07' 'AL' 'S05' 'HDL' 'S15' 'MIA'
 'UL' 'S13' 'MC' 'S01' 'S11' 'AL/2' 'S29' ' UL' 'UL ' 'S15 ' 'M' 'S19' 'H'
 ' OFF' 'S12' 'S' 'A/2' '  AL' 'S21' 'Longleave']

,Date,Ecode,Name,Email,Role,Shift,Slot,Values
74361,2023-08-01,3221965.0,NGUYỄN QUỲNH TRANG,trang.nq2@trans-cosmos.com.vn,SOM,S05,06:00,_
74362,2023-08-01,3191265.0,PHẠM THỊ PHÚ,phu.pt@trans-cosmos.com.vn,OM,S07,06:00,_
74363,2023-08-01,3222368.0,NGUYỄN THỊ HẢI YẾN,yen.nth@trans-cosmos.com.vn,OM,S07,06:00,_
74364,2023-08-01,3230317.0,NGUYỄN THỊ DUNG,dung.nt2@trans-cosmos.com.vn,OM,S07,06:00,_
74365,2023-08-01,3230978.0,TRẦN TỐ UYÊN,uyen.tt2@trans-cosmos.com.vn,OM,S05,06:00,_
...,...,...,...,...,...,...,...,...
2182245,2023-08-27,3231692.0,NGUYỄN PHẠM HUỲNH PHƯƠNG THANH,thanh.nph@trans-cosmos.com.vn,Operator,OFF,NaN,_
2182246,2023-08-27,3231694.0,ĐÀM KHẮC THUẬN,thuan.dk@trans-cosmos.com.vn,Operator,S29,NaN,_
2182247,2023-08-27,3231695.0,NGUYỄN THỊ THẮM,tham.nt2@trans-cosmos.com.vn,Operator,OFF,NaN,_
2182248,2023-08-27,3231698.0,LÊ XUÂN TRÚC,truc.lx@trans-cosmos.com.vn,Operator,S07,NaN,_
2182249,2023-08-27,3231701.0,NGUYỄN TRẦN THỤC UYÊN,uyen.ntt3@trans-cosmos.com.vn,QA,S09,NaN,_

In [10]:
Link_QA_Sampling_Cases = 'D:/Shrinkage/Shrinkage rawdata.xlsx'
shrinkage_workbook = pd.ExcelFile(Link_QA_Sampling_Cases)
shrinkage_sheets = shrinkage_workbook.sheet_names

queue_list = pd.read_excel('D:/Code/Code/Support_dashboard.xlsx',sheet_name='Queue List').values
queue_list = pd.DataFrame(queue_list)
headers = ['BUSINESS','COMPOUND','CATEGORY','MOD QUEUE ID','MOD QUEUE NAME',
           'QA QUEUE ID','QA QUEUE NAME','QUEUE GROUP','STATUS','Priority','Latency','AHT (secs)','Policy_type','Classify']
queue_list.columns = headers

shrinkage_rawdata = pd.concat([pd.read_excel(shrinkage_workbook, sheet_name=s).assign(sheet_name=s) for s in shrinkage_sheets])
shrinkage_rawdata = shrinkage_rawdata.rename(columns={'sheet_name':'Month'})
Shrinkage_Data = pd.melt(shrinkage_rawdata, id_vars=['Month','E.Code','FullName','Email','Task','Coumpound','Role','Batch','LineManager','Emp Type'], var_name='Date', value_name='Shift')
Shrinkage_Data['Date'] = pd.to_datetime(Shrinkage_Data['Date'].apply(convert_datetime))
Shrinkage_Data =  Shrinkage_Data[(Shrinkage_Data['Date'].dt.strftime('%Y-%m-%d') >= from_Date) & (Shrinkage_Data['Date'].dt.strftime('%Y-%m-%d') <= to_Date)]

schedule_rule = pd.read_excel('D:/Code/Code/Support_dashboard.xlsx',sheet_name='Schedule_rule')
schedule_rule = schedule_rule[['ShiftCode','Start Time (Hour)','End Time (Hour)','Start Lunch (Hour)','End Lunch (Hour)','Lunch (Duration)']]
schedule_rule = schedule_rule.fillna("---")

working_hour_rawdata = merge_csv_files('D:/Shrinkage/Working Shift')
working_hour_rawdata_columns = ['Date','Email','Department','Status','Status detail','Remarks','Hours(h)','Start_time','End_time','Shift','Shift Date','No. of task','Schedule or not','Inconsistency or not','Resigned or not','Month_files']
working_hour_rawdata.columns = working_hour_rawdata_columns
working_hour_rawdata = working_hour_rawdata[['Date','Email','Department','Status','Status detail','Start_time','End_time','No. of task']]
working_hour_rawdata['Start_time'] = pd.to_datetime(working_hour_rawdata['Start_time'])
working_hour_rawdata['End_time'] = pd.to_datetime(working_hour_rawdata['End_time'])
working_hour_rawdata = working_hour_rawdata[working_hour_rawdata['Status']!="Offline"]
working_hour_rawdata = working_hour_rawdata.sort_values(by='Start_time',ascending=True)

data_full_alternation = pd.read_excel('D:/Code/Code/linemanager_full.xlsx')
data_full_alternation = data_full_alternation[['EffectDate','FullName','Email','LineManager','Role','ProductionTenure']]

volume_rawdata = merge_csv_files('D:/Shrinkage/Volume Hourly')
volume_hourly_rawdata = volume_rawdata[['Date', 'Queue Title', 'Moderator', 'Department Name', 'Queue ID','No. of Moderation Tasks','Avg. Handling Time(s)']]
volume_hourly_rawdata['Date'] = pd.to_datetime(volume_hourly_rawdata['Date'])
volume_hourly_rawdata['Slot'] = volume_hourly_rawdata['Date'].dt.strftime('%H:%M')
volume_hourly_rawdata['Date'] = pd.to_datetime(volume_hourly_rawdata['Date'].apply(convert_datetime))
volume_hourly_rawdata = volume_hourly_rawdata[(volume_hourly_rawdata['Date'].dt.strftime('%Y-%m-%d') >= from_Date) & (volume_hourly_rawdata['Date'].dt.strftime('%Y-%m-%d') <= to_Date)]
volume_hourly_rawdata['Slot'].unique()

C:\Users\v6210227\AppData\Local\Temp\ipykernel_19288\1414075056.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  volume_hourly_rawdata['Date'] = pd.to_datetime(volume_hourly_rawdata['Date'])
C:\Users\v6210227\AppData\Local\Temp\ipykernel_19288\1414075056.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  volume_hourly_rawdata['Slot'] = volume_hourly_rawdata['Date'].dt.strftime('%H:%M')
C:\Users\v6210227\AppData\Local\Temp\ipykernel_19288\1414075056.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  volume_hourly_rawdata['Date'] = pd.to_datetime(volume_hourly_rawdata['Date'].apply(convert_datetime))

array(['00:00', '06:00', '07:00', '08:00', '09:00', '10:00', '11:00',
       '12:00', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00',
       '01:00', '02:00', '03:00', '04:00', '05:00', '20:00', '21:00',
       '22:00', '23:00', '19:00'], dtype=object)

In [11]:
# volume_daily_rawdata = merge_csv_files('D:/Shrinkage/Volume daily')
# volume_daily_rawdata = volume_daily_rawdata[['title','1_verifier','1_resolve_time','1_duration']]
# volume_daily_rawdata['1_resolve_time'] = pd.to_datetime(volume_daily_rawdata['1_resolve_time'].apply(convert_time))
# volume_daily_rawdata['Date'] = pd.to_datetime(volume_daily_rawdata['1_resolve_time'].apply(convert_datetime))
# volume_daily_rawdata = volume_daily_rawdata[(volume_daily_rawdata['Date'].dt.strftime('%Y-%m-%d') >= from_Date) & (volume_daily_rawdata['Date'].dt.strftime('%Y-%m-%d') <= to_Date)]

# pv_volume_daily = pd.pivot_table(volume_daily_rawdata,values='1_verifier',index=['title'],columns='Date',aggfunc='count')
# pv_volume_daily = pv_volume_daily.fillna("---")
# pv_volume_daily = pv_volume_daily.reset_index()
# pv_volume_daily

In [12]:
working_hour_rawdata

,Date,Email,Department,Status,Status detail,Start_time,End_time,No. of task
10430,4/1/2023,thai.tq1@trans-cosmos.com.vn,TL DUC THANH,Moderation Task,Queue moderation,2023-04-01 00:00:00,2023-04-01 02:24:00,122
74780,4/1/2023,linh.vta@trans-cosmos.com.vn,TL XUAN DAT,Moderation Task,Queue moderation,2023-04-01 00:00:00,2023-04-01 01:00:00,48
99066,4/1/2023,tai.lh@trans-cosmos.com.vn,MOD15,Idle,NaN,2023-04-01 00:00:00,2023-04-01 13:30:00,17
80776,4/1/2023,san.cb1@trans-cosmos.com.vn,TL MINH TAN,Rest,Meal break,2023-04-01 00:00:00,2023-04-01 01:00:00,0
96774,4/1/2023,tuan.nv@trans-cosmos.com.vn,MOD15,Idle,NaN,2023-04-01 00:00:00,2023-04-05 16:06:00,142
...,...,...,...,...,...,...,...,...
669982,8/26/2023,ngoc.vtk@trans-cosmos.com.vn,TL DOAN THUAN,Moderation Task,Queue moderation,2023-08-26 23:58:00,2023-08-26 23:59:00,2
679858,8/26/2023,linh.lp@trans-cosmos.com.vn,TL VINH HUNG,Moderation Task,Queue moderation,2023-08-26 23:58:00,2023-08-26 23:59:00,2
677287,8/26/2023,ngan.nhb@trans-cosmos.com.vn,TL MINH HAI,Moderation Task,Queue moderation,2023-08-26 23:58:00,2023-08-26 23:59:00,0
665392,8/26/2023,loc.pt@trans-cosmos.com.vn,TL THANH PHI,Moderation Task,Queue moderation,2023-08-26 23:59:00,2023-08-26 23:59:00,0
678356,8/26/2023,chuong.lv@trans-cosmos.com.vn,TL THANH THAO,Moderation Task,Queue moderation,2023-08-26 23:59:00,2023-08-26 23:59:00,0

In [13]:
import datetime
new_rows = []
status_list = working_hour_rawdata['Status'].unique()

for index, row in working_hour_rawdata.iterrows():
    start_time = row['Start_time']
    end_time = row['End_time']
    status = row['Status']
    
    if start_time.date() == end_time.date():
        duration = end_time - start_time

        if start_time.hour == end_time.hour:
            new_row = {
                'Date': start_time.date(),
                'Email': row['Email'],
                'Department': row['Department'],
                'Status': status,
                'Status detail': row['Status detail'], 
                'Start_time': start_time,
                'End_time': end_time - datetime.timedelta(seconds=1)}
            new_rows.append(new_row)
        else:
            while start_time.hour < end_time.hour:
                next_hour = start_time.replace(minute=59, second=59)
                new_row = {
                    'Date': start_time.date(),
                    'Email': row['Email'],
                    'Department': row['Department'],
                    'Status': status,
                    'Status detail': row['Status detail'], 
                    'Start_time': start_time,
                    'End_time': next_hour}
                new_rows.append(new_row)
                start_time = next_hour + datetime.timedelta(seconds=1)
                start_time = start_time.replace(minute=0, second=0)

            new_row = { 
                'Date': start_time.date(),
                'Email': row['Email'],
                'Department': row['Department'],
                'Status': status,
                'Status detail': row['Status detail'], 
                'Start_time': start_time,
                'End_time': end_time - datetime.timedelta(seconds=1)}
            new_rows.append(new_row)
    else:
        current_date = start_time.date()
        while current_date <= end_time.date():
            if current_date == start_time.date():
                start_hour = start_time.hour
                end_hour = 23
            elif current_date == end_time.date():
                start_hour = 0
                end_hour = end_time.hour
            else:
                start_hour = 0
                end_hour = 23

            for hour in range(start_hour, end_hour + 1):
                if current_date == start_time.date() and hour == start_time.hour:
                    start_datetime = start_time
                else:
                    start_datetime = datetime.datetime.combine(current_date, datetime.time(hour, 0, 0))

                if current_date == end_time.date() and hour == end_time.hour:
                    end_datetime = end_time - datetime.timedelta(seconds=1)
                else:
                    end_datetime = datetime.datetime.combine(current_date, datetime.time(hour, 59, 59))
                    
                if start_datetime >= start_time and end_datetime <= end_time:
                    new_row = {
                        'Date': current_date,
                        'Email': row['Email'],
                        'Department': row['Department'],
                        'Status': status,
                        'Status detail': row['Status detail'], 
                        'Start_time': start_datetime,
                        'End_time': end_datetime}
                    new_rows.append(new_row)
            current_date += datetime.timedelta(days=1)

expanded_working_hour = pd.DataFrame(new_rows)
from datetime import datetime

In [14]:
expanded_working_hour['Duration (h)'] = expanded_working_hour['End_time'] - expanded_working_hour['Start_time']
expanded_working_hour['Duration (h)'] = expanded_working_hour['Duration (h)'] / pd.Timedelta(hours=1)
expanded_working_hour['Duration (m)'] = expanded_working_hour['Duration (h)'] * 60
expanded_working_hour['Duration (h)'] = expanded_working_hour['Duration (h)']
expanded_working_hour['Duration (m)'] = expanded_working_hour['Duration (m)']

import datetime

def classify_slot(time):
    hour = time.hour
    slot_time = datetime.datetime(time.year, time.month, time.day, hour)
    return slot_time

expanded_working_hour['Slot'] = expanded_working_hour['Start_time'].apply(classify_slot)
expanded_working_hour['Slot'] = expanded_working_hour['Slot'].apply(lambda x: x.strftime("%H:%M"))
# expanded_working_hour['Start time'] = expanded_working_hour['Start_time'].apply(lambda x: x.strftime("%H:%M"))
# expanded_working_hour['End time'] = expanded_working_hour['End_time'].apply(lambda x: x.strftime("%H:%M"))

from datetime import datetime
expanded_working_hour['Date'] = pd.to_datetime(expanded_working_hour['Date'].apply(convert_datetime))
expanded_working_hour = expanded_working_hour[expanded_working_hour['Duration (m)']>0]

In [15]:
Shrinkage_Data = Shrinkage_Data.dropna(subset=['Shift'])
Shrinkage_Data = pd.merge(Shrinkage_Data,schedule_rule,how='left',left_on='Shift' ,right_on='ShiftCode')
Shrinkage_Data['Start Shift (h)'] = pd.to_datetime(Shrinkage_Data['Start Time (Hour)'], format='%I:%M %p', errors='coerce')
Shrinkage_Data['End Shift (h)'] = pd.to_datetime(Shrinkage_Data['End Time (Hour)'], format='%I:%M %p', errors='coerce')
Shrinkage_Data['Start Shift (h)'] = Shrinkage_Data['Start Shift (h)'].dt.strftime('%H:%M')
Shrinkage_Data['End Shift (h)'] = Shrinkage_Data['End Shift (h)'].dt.strftime('%H:%M')
schedule = pd.merge(Shrinkage_Data,expanded_working_hour,how='left',left_on=['Date','Email'],right_on=['Date','Email'])
schedule_merged = pd.merge(schedule,mod_interval_hour,how='left',left_on=['Date','Email','Slot','Shift'],right_on=['Date','Email','Slot','Shift'])
schedule_merged = schedule_merged.drop(schedule_merged[schedule_merged['Duration (m)'] < 1].index)
schedule_merged = schedule_merged.drop_duplicates()
# schedule_merged['Start time'] = schedule_merged['Start_time'].dt.strftime('%H:%M')
# schedule_merged['End time'] = schedule_merged['End_time'].dt.strftime('%H:%M')
schedule_merged['Start_shift'] = pd.to_datetime(schedule_merged['Date'].dt.strftime('%Y-%m-%d') + ' ' + schedule_merged['Start Shift (h)'])
schedule_merged['End_shift'] = pd.to_datetime(schedule_merged['Date'].dt.strftime('%Y-%m-%d') + ' ' + schedule_merged['End Shift (h)'])
schedule_merged = schedule_merged.sort_values(by=['Email','Start_time'],ascending = True)
schedule_merged = pd.merge(schedule_merged,data_full_alternation,how='left',left_on=['Date', 'FullName','Email'],right_on=['EffectDate', 'FullName','Email'],suffixes=('','_full'))
print(schedule_merged.columns)
schedule_detail = schedule_merged[['Date', 'LineManager_full', 'Email','Coumpound', 'Shift', 'Slot', 'Status', 'Status detail', 'Duration (m)','Start_shift','End_shift','Start_time', 'End_time','Values']]
schedule_detail.fillna('')
try:
   schedule_detail.to_excel('D:/Shrinkage/schedule_detail.xlsx')
except:
   pass

Index(['Month', 'E.Code', 'FullName', 'Email', 'Task', 'Coumpound', 'Role_x',
       'Batch', 'LineManager', 'Emp Type', 'Date', 'Shift', 'ShiftCode',
       'Start Time (Hour)', 'End Time (Hour)', 'Start Lunch (Hour)',
       'End Lunch (Hour)', 'Lunch (Duration)', 'Start Shift (h)',
       'End Shift (h)', 'Department', 'Status', 'Status detail', 'Start_time',
       'End_time', 'Duration (h)', 'Duration (m)', 'Slot', 'Ecode', 'Name',
       'Role_y', 'Values', 'Start_shift', 'End_shift', 'EffectDate',
       'LineManager_full', 'Role', 'ProductionTenure'],
      dtype='object')

In [16]:
schedule_detail

,Date,LineManager_full,Email,Coumpound,Shift,Slot,Status,Status detail,Duration (m),Start_shift,End_shift,Start_time,End_time,Values
0,2023-08-02,NGUYỄN THANH PHI,an.hb2@trans-cosmos.com.vn,Trooper,S01,06:00,Moderation Task,Queue moderation,59.983333,2023-08-02 06:00:00,2023-08-02 15:00:00,2023-08-02 06:00:00,2023-08-02 06:59:59,Counterfeit
1,2023-08-02,NGUYỄN THANH PHI,an.hb2@trans-cosmos.com.vn,Trooper,S01,07:00,Moderation Task,Queue moderation,59.983333,2023-08-02 06:00:00,2023-08-02 15:00:00,2023-08-02 07:00:00,2023-08-02 07:59:59,Counterfeit
2,2023-08-02,NGUYỄN THANH PHI,an.hb2@trans-cosmos.com.vn,Trooper,S01,08:00,Moderation Task,Queue moderation,59.983333,2023-08-02 06:00:00,2023-08-02 15:00:00,2023-08-02 08:00:00,2023-08-02 08:59:59,Counterfeit
3,2023-08-02,NGUYỄN THANH PHI,an.hb2@trans-cosmos.com.vn,Trooper,S01,09:00,Moderation Task,Queue moderation,59.983333,2023-08-02 06:00:00,2023-08-02 15:00:00,2023-08-02 09:00:00,2023-08-02 09:59:59,Counterfeit
4,2023-08-02,NGUYỄN THANH PHI,an.hb2@trans-cosmos.com.vn,Trooper,S01,10:00,Rest,Meal break,58.983333,2023-08-02 06:00:00,2023-08-02 15:00:00,2023-08-02 10:01:00,2023-08-02 10:59:59,L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204946,2023-08-27,NGUYỄN THANH PHI,yen.tln@trans-cosmos.com.vn,Trooper,S05,NaN,NaN,NaN,NaN,2023-08-27 08:00:00,2023-08-27 17:00:00,NaT,NaT,_
204947,2023-08-28,NGUYỄN THANH PHI,yen.tln@trans-cosmos.com.vn,Trooper,S07,NaN,NaN,NaN,NaN,2023-08-28 09:00:00,2023-08-28 18:00:00,NaT,NaT,NaN
204948,2023-08-29,NGUYỄN THANH PHI,yen.tln@trans-cosmos.com.vn,Trooper,S05,NaN,NaN,NaN,NaN,2023-08-29 08:00:00,2023-08-29 17:00:00,NaT,NaT,NaN
204949,2023-08-30,NGUYỄN THANH PHI,yen.tln@trans-cosmos.com.vn,Trooper,S01,NaN,NaN,NaN,NaN,2023-08-30 06:00:00,2023-08-30 15:00:00,NaT,NaT,NaN
204950,2023-08-31,NGUYỄN THANH PHI,yen.tln@trans-cosmos.com.vn,Trooper,OFF,NaN,NaN,NaN,NaN,NaT,NaT,NaT,NaT,NaN

In [17]:
night_shift = ['S20','S21','S22','S23','S24','S25','S26','S27','S28','S29','S30','S31','S32','S33','OFF','AL','UL','AL/2','MIA','MC','LongLeave','HDL','S','R']
day_shift = ['S01','S02','S03','S04','S05','S06','S07','S08','S09','S10','S11','S12','S13','S14','S15','S16','S17','S18','S19','OFF','AL','UL','AL/2','MIA','MC','LongLeave','HDL','S','R']

checking_schedule_temp = schedule_merged[['Date','LineManager_full','FullName','Email','Shift','Status','Status detail','Start Shift (h)', 'End Shift (h)','Start_time','End_time','Duration (m)','Slot','Values']]

dayS_schedule = checking_schedule_temp[checking_schedule_temp['Shift'].isin(day_shift)]
dayS_schedule = dayS_schedule.groupby(by=['Date','LineManager_full','FullName','Email','Shift','Start Shift (h)', 'End Shift (h)'],as_index = False).agg({'Start_time':'min','End_time':'max'})
dayS_schedule['Date+1']  = dayS_schedule['Date'] + timedelta(days=1)
dayS_schedule['Start_shift'] = dayS_schedule['Date'].dt.strftime('%Y-%m-%d')
dayS_schedule['Start_shift'] = pd.to_datetime(dayS_schedule['Date'].dt.strftime('%Y-%m-%d') + ' ' + dayS_schedule['Start Shift (h)'])
dayS_schedule['End_shift'] = dayS_schedule['Date'].dt.strftime('%Y-%m-%d')
dayS_schedule['End_shift'] = pd.to_datetime(dayS_schedule['Date'].dt.strftime('%Y-%m-%d') + ' ' + dayS_schedule['End Shift (h)'])
if (dayS_schedule['Start_shift'] > dayS_schedule['End_shift']).any():
    dayS_schedule.loc[dayS_schedule['Start_shift'] > dayS_schedule['End_shift'], 'End_shift'] += pd.DateOffset(days=1)
dayS_schedule['gap_start'] = round((dayS_schedule['Start_shift'] - dayS_schedule['Start_time']).dt.total_seconds() / 60,1)
dayS_schedule['gap_end'] = round((dayS_schedule['End_shift'] - dayS_schedule['End_time']).dt.total_seconds() / 60,1)
dayS_schedule['deliver'] = round((dayS_schedule['End_time'] - dayS_schedule['Start_time']).dt.total_seconds() / 60,1)

nightS_schedule = checking_schedule_temp[checking_schedule_temp['Shift'].isin(night_shift)]
nightS_schedule['Fake_Date'] = nightS_schedule.apply(lambda row: row['Date'] - pd.DateOffset(days=1) if (row['Start_time'].hour < 12) else row['Date'],axis=1)
nightS_schedule = nightS_schedule.drop('Date', axis=1)
nightS_schedule = nightS_schedule.rename(columns={'Fake_Date':'Date'})
nightS_schedule = nightS_schedule.sort_values(by=['Email','Date'],ascending = True)

nightS_schedule['Shift'] = nightS_schedule.groupby(['Date', 'Email'])['Shift'].transform('first')
nightS_schedule['Start Shift (h)'] = nightS_schedule.groupby(['Date', 'Email'])['Start Shift (h)'].transform('first')
nightS_schedule['End Shift (h)'] = nightS_schedule.groupby(['Date', 'Email'])['End Shift (h)'].transform('first')

nightS_schedule = nightS_schedule.groupby(by=['Date','LineManager_full','FullName','Email','Shift','Start Shift (h)', 'End Shift (h)'],as_index = False).agg({'Start_time':'min','End_time':'max'})
nightS_schedule = nightS_schedule.rename(columns={'Fake_Date':'Date'})
nightS_schedule['Date+1']  = nightS_schedule['Date'] + timedelta(days=1)
nightS_schedule['Start_shift'] = nightS_schedule['Date'].dt.strftime('%Y-%m-%d')
nightS_schedule['Start_shift'] = pd.to_datetime(nightS_schedule['Date'].dt.strftime('%Y-%m-%d') + ' ' + nightS_schedule['Start Shift (h)'])
nightS_schedule['End_shift'] = nightS_schedule['Date+1'].dt.strftime('%Y-%m-%d')
nightS_schedule['End_shift'] = pd.to_datetime(nightS_schedule['Date+1'].dt.strftime('%Y-%m-%d') + ' ' + nightS_schedule['End Shift (h)'])
nightS_schedule['gap_start'] = round((nightS_schedule['Start_shift'] - nightS_schedule['Start_time']).dt.total_seconds() / 60,1)
nightS_schedule['gap_end'] = round((nightS_schedule['End_shift'] - nightS_schedule['End_time']).dt.total_seconds() / 60,1)
nightS_schedule['deliver'] = round((nightS_schedule['End_time'] - nightS_schedule['Start_time']).dt.total_seconds() / 60,1)

checking_schedule_gr = pd.concat([dayS_schedule,nightS_schedule], axis = 0)

checking_schedule_gr.loc[(checking_schedule_gr['gap_start'] < -2), 'Violation'] = f"Sign in - Late"
checking_schedule_gr.loc[(checking_schedule_gr['gap_end'] > 2), 'Violation'] = f"Sign out - Early"
checking_schedule_gr.loc[(checking_schedule_gr['gap_start'] < -30) & (checking_schedule_gr['deliver'] <= 540), 'Violation'] = "Sign in - Late - Not enough first hour"
checking_schedule_gr.loc[(checking_schedule_gr['gap_end'] > 30) & (checking_schedule_gr['deliver'] <= 540), 'Violation'] = "Sign out - Early - Not enough last hour"
checking_schedule_gr.loc[(checking_schedule_gr['gap_start'] > 30) & (checking_schedule_gr['gap_end'] > 30) & (checking_schedule_gr['deliver'] <= 540), 'Violation'] = "Wrong Shift - Early"
checking_schedule_gr.loc[(checking_schedule_gr['gap_start'] < -30) & (checking_schedule_gr['gap_end'] < -30) & (checking_schedule_gr['deliver'] <= 540), 'Violation'] = "Wrong Shift - Late"
checking_schedule_gr.loc[(~checking_schedule_gr['Shift'].isin(['HDL','AL/2'])) & (checking_schedule_gr['deliver'] <= 510), 'Violation'] = "Not enough hour"
checking_schedule_gr = checking_schedule_gr[~checking_schedule_gr['Start_time'].isnull()]

import datetime
def classify_slot(time):
    hour = time.hour
    slot_time = datetime.datetime(time.year, time.month, time.day, hour)
    return slot_time

checking_schedule_gr['Start_time'] = pd.to_datetime(checking_schedule_gr['Start_time'])
checking_schedule_gr['Slot'] = checking_schedule_gr['Start_time'].apply(classify_slot)
checking_schedule_gr['Slot'] = checking_schedule_gr['Slot'].apply(lambda x: x.strftime("%H:%M"))
from datetime import datetime

violation_tracking = checking_schedule_gr[['Date','LineManager_full', 'FullName', 'Email','Shift','Start_shift','End_shift','Slot','Start_time', 'End_time','gap_start', 'gap_end', 'deliver','Violation']]
violation_tracking.fillna('')
print(violation_tracking.columns)
try:
    violation_tracking.to_excel('D:/Shrinkage/violation_tracking.xlsx')
except:
    pass

C:\Users\v6210227\AppData\Local\Temp\ipykernel_19288\1774436015.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nightS_schedule['Fake_Date'] = nightS_schedule.apply(lambda row: row['Date'] - pd.DateOffset(days=1) if (row['Start_time'].hour < 12) else row['Date'],axis=1)

Index(['Date', 'LineManager_full', 'FullName', 'Email', 'Shift', 'Start_shift',
       'End_shift', 'Slot', 'Start_time', 'End_time', 'gap_start', 'gap_end',
       'deliver', 'Violation'],
      dtype='object')

In [18]:
violation_tracking

,Date,LineManager_full,FullName,Email,Shift,Start_shift,End_shift,Slot,Start_time,End_time,gap_start,gap_end,deliver,Violation
0,2023-08-01,BÙI THỊ THANH THẢO,BÙI THỊ CÁT THI,thi.btc@trans-cosmos.com.vn,S09,2023-08-01 10:00:00,2023-08-01 19:00:00,10:00,2023-08-01 10:00:00,2023-08-01 18:59:59,0.0,0.0,540.0,NaN
1,2023-08-01,BÙI THỊ THANH THẢO,HÀ PHẠM TÚ ANH,anh.hpt@trans-cosmos.com.vn,S19,2023-08-01 15:00:00,2023-08-02 00:00:00,15:00,2023-08-01 15:00:00,2023-08-01 23:59:59,0.0,0.0,540.0,NaN
2,2023-08-01,BÙI THỊ THANH THẢO,LÊ CÔNG HẬU,hau.lc@trans-cosmos.com.vn,S01,2023-08-01 06:00:00,2023-08-01 15:00:00,06:00,2023-08-01 06:00:00,2023-08-01 14:59:59,0.0,0.0,540.0,NaN
3,2023-08-01,BÙI THỊ THANH THẢO,LÊ MINH NHẬT,nhat.lm@trans-cosmos.com.vn,S11,2023-08-01 11:00:00,2023-08-01 20:00:00,10:00,2023-08-01 10:58:00,2023-08-01 20:01:59,2.0,-2.0,544.0,NaN
4,2023-08-01,BÙI THỊ THANH THẢO,LÊ VĂN CHƯƠNG,chuong.lv@trans-cosmos.com.vn,S17,2023-08-01 14:00:00,2023-08-01 23:00:00,14:00,2023-08-01 14:00:00,2023-08-01 22:59:59,0.0,0.0,540.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2315,2023-08-26,VÕ TẤN LỰC,TRẦN MINH KHOA,khoa.tm@trans-cosmos.com.vn,S29,2023-08-26 20:00:00,2023-08-27 05:00:00,20:00,2023-08-26 20:00:00,2023-08-26 23:58:59,0.0,301.0,239.0,Not enough hour
2316,2023-08-26,VÕ TẤN LỰC,VI THỊ GIANG,giang.vt1@trans-cosmos.com.vn,S29,2023-08-26 20:00:00,2023-08-27 05:00:00,19:00,2023-08-26 19:55:00,2023-08-26 23:58:59,5.0,301.0,244.0,Not enough hour
2317,2023-08-26,VÕ TẤN LỰC,VŨ THUỴ HỒNG NGỌC THUỶ,thuy.vthn2@trans-cosmos.com.vn,S29,2023-08-26 20:00:00,2023-08-27 05:00:00,19:00,2023-08-26 19:56:00,2023-08-26 23:58:59,4.0,301.0,243.0,Not enough hour
2318,2023-08-26,VÕ TẤN LỰC,ĐOÀN MAI PHÚ,phu.dm@trans-cosmos.com.vn,S29,2023-08-26 20:00:00,2023-08-27 05:00:00,19:00,2023-08-26 19:54:00,2023-08-26 23:58:59,6.0,301.0,245.0,Not enough hour
2319,2023-08-26,VÕ TẤN LỰC,ĐỖ HOÀNG PHƯƠNG LINH,linh.dhp@trans-cosmos.com.vn,S33,2023-08-26 22:00:00,2023-08-27 07:00:00,22:00,2023-08-26 22:00:00,2023-08-26 23:58:59,0.0,421.0,119.0,Not enough hour

In [19]:
volume_hourly_rawdata = volume_hourly_rawdata[~volume_hourly_rawdata['Queue Title'].str.contains('Juren')]
volume_hourly_grouped = volume_hourly_rawdata.groupby(['Date','Queue Title','Moderator', 'Slot']).agg({'No. of Moderation Tasks': 'sum','Avg. Handling Time(s)':'mean'}).reset_index()
volume_hourly_grouped = pd.merge(volume_hourly_grouped,queue_list,how='left',left_on =['Queue Title'],right_on=['MOD QUEUE NAME'])
volume_hourly_grouped = pd.merge(volume_hourly_grouped,data_full_alternation,how='left',left_on=['Date','Moderator'],right_on=['EffectDate','Email'],suffixes=('','_full'))
volume_slot = volume_hourly_grouped[['Date','Classify','Queue Title','LineManager','Email', 'Slot','No. of Moderation Tasks','Avg. Handling Time(s)']]
volume_slot = volume_slot.drop_duplicates()
try:
   volume_slot.to_excel('D:/Shrinkage/volume_slot.xlsx')
except:
   pass

In [20]:
volume_slot

,Date,Classify,Queue Title,LineManager,Email,Slot,No. of Moderation Tasks,Avg. Handling Time(s)
0,2023-08-01,NaN,Global-Ecom-Governance-IPR-Product-Black-Img,ĐỖ PHƯƠNG TRINH,an.nhh@trans-cosmos.com.vn,14:00,15,70.34047
1,2023-08-01,NaN,Global-Ecom-Governance-IPR-Product-Black-Img,ĐỖ PHƯƠNG TRINH,an.nhh@trans-cosmos.com.vn,15:00,7,57.87557
2,2023-08-01,NaN,Global-Ecom-Governance-IPR-Product-Black-Img,ĐỖ PHƯƠNG TRINH,an.nhh@trans-cosmos.com.vn,16:00,16,38.83881
3,2023-08-01,NaN,Global-Ecom-Governance-IPR-Product-Black-Img,ĐỖ PHƯƠNG TRINH,an.nhh@trans-cosmos.com.vn,17:00,1,266.16600
4,2023-08-01,NaN,Global-Ecom-Governance-IPR-Product-Black-Img,NaN,NaN,16:00,15,6.46260
...,...,...,...,...,...,...,...,...
279449,2023-08-26,QA moderated,[VN_CB]Shop Product Appeal Audit,NGUYỄN HUY DANH,quyen.tt3@trans-cosmos.com.vn,15:00,10,150.30840
279450,2023-08-26,QA moderated,[VN_CB]Shop Product Appeal Audit,NGUYỄN HUY DANH,quyen.tt3@trans-cosmos.com.vn,16:00,4,90.80675
279451,2023-08-26,QA moderated,[VN_CB]Shop Product Appeal Audit,NGUYỄN HUY DANH,quyen.tt3@trans-cosmos.com.vn,17:00,1,79.10000
279452,2023-08-26,QA moderated,[VN_CB]Shop Product Appeal Audit,NGUYỄN HUY DANH,quyen.tt3@trans-cosmos.com.vn,18:00,3,157.75167
279453,2023-08-26,QA moderated,【UG-2R-GnE】TTS-vi-VN,NGUYỄN THANH PHI,quy.hlc@trans-cosmos.com.vn,06:00,2,4.02950

In [21]:
final_schedule = schedule_merged[['Date','LineManager_full','FullName','Email','Shift','Slot','Status','Start_shift','End_shift','Start_time','End_time']]
final_schedule

,Date,LineManager_full,FullName,Email,Shift,Slot,Status,Start_shift,End_shift,Start_time,End_time
0,2023-08-02,NGUYỄN THANH PHI,HUỲNH BỘI AN,an.hb2@trans-cosmos.com.vn,S01,06:00,Moderation Task,2023-08-02 06:00:00,2023-08-02 15:00:00,2023-08-02 06:00:00,2023-08-02 06:59:59
1,2023-08-02,NGUYỄN THANH PHI,HUỲNH BỘI AN,an.hb2@trans-cosmos.com.vn,S01,07:00,Moderation Task,2023-08-02 06:00:00,2023-08-02 15:00:00,2023-08-02 07:00:00,2023-08-02 07:59:59
2,2023-08-02,NGUYỄN THANH PHI,HUỲNH BỘI AN,an.hb2@trans-cosmos.com.vn,S01,08:00,Moderation Task,2023-08-02 06:00:00,2023-08-02 15:00:00,2023-08-02 08:00:00,2023-08-02 08:59:59
3,2023-08-02,NGUYỄN THANH PHI,HUỲNH BỘI AN,an.hb2@trans-cosmos.com.vn,S01,09:00,Moderation Task,2023-08-02 06:00:00,2023-08-02 15:00:00,2023-08-02 09:00:00,2023-08-02 09:59:59
4,2023-08-02,NGUYỄN THANH PHI,HUỲNH BỘI AN,an.hb2@trans-cosmos.com.vn,S01,10:00,Rest,2023-08-02 06:00:00,2023-08-02 15:00:00,2023-08-02 10:01:00,2023-08-02 10:59:59
...,...,...,...,...,...,...,...,...,...,...,...
204946,2023-08-27,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,S05,NaN,NaN,2023-08-27 08:00:00,2023-08-27 17:00:00,NaT,NaT
204947,2023-08-28,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,S07,NaN,NaN,2023-08-28 09:00:00,2023-08-28 18:00:00,NaT,NaT
204948,2023-08-29,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,S05,NaN,NaN,2023-08-29 08:00:00,2023-08-29 17:00:00,NaT,NaT
204949,2023-08-30,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,S01,NaN,NaN,2023-08-30 06:00:00,2023-08-30 15:00:00,NaT,NaT
204950,2023-08-31,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,OFF,NaN,NaN,NaT,NaT,NaT,NaT

In [22]:
# final_schedule = schedule_merged[['Date','LineManager_full','FullName','Email','Shift','Slot','Status','Start_shift','End_shift','Start_time','End_time']]

# final_schedule['No. of Moderation Task'] = 0
# final_schedule['AHT (s)'] = 0

# for index, row in final_schedule.iterrows():
#     email = row['Email']
#     start_time = row['Start_time']
#     end_time = row['End_time']
#     status = row['Status']
    
#     if status == 'Moderation Task' and pd.notnull(start_time) and pd.notnull(end_time):
#         filtered_rows = volume_daily_rawdata.loc[
#             (volume_daily_rawdata['1_verifier'] == email) &
#             (pd.to_datetime(volume_daily_rawdata['1_resolve_time']) >= start_time) &
#             (pd.to_datetime(volume_daily_rawdata['1_resolve_time']) <= end_time)]

#         num_moderation_tasks = len(filtered_rows)
#         average_duration = filtered_rows['1_duration'].mean()

#         final_schedule.at[index, 'No. of Moderation Task'] = num_moderation_tasks
#         final_schedule.at[index, 'AHT (s)'] = average_duration

#         print(f"Mod: {email}, Start: {start_time}, End: {end_time}, No. Task: {num_moderation_tasks} - AHT(s): {average_duration}")

In [23]:
final_schedule['Duration (m)'] = ((final_schedule['End_time'] - final_schedule['Start_time'])/ pd.Timedelta(hours=1)) * 60

C:\Users\v6210227\AppData\Local\Temp\ipykernel_19288\2710032584.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_schedule['Duration (m)'] = ((final_schedule['End_time'] - final_schedule['Start_time'])/ pd.Timedelta(hours=1)) * 60

In [24]:
final_schedule[final_schedule['Email']=='yen.tln@trans-cosmos.com.vn']

,Date,LineManager_full,FullName,Email,Shift,Slot,Status,Start_shift,End_shift,Start_time,End_time,Duration (m)
204532,2023-08-01,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,S05,08:00,Moderation Task,2023-08-01 08:00:00,2023-08-01 17:00:00,2023-08-01 08:00:00,2023-08-01 08:59:59,59.983333
204533,2023-08-01,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,S05,09:00,Moderation Task,2023-08-01 08:00:00,2023-08-01 17:00:00,2023-08-01 09:00:00,2023-08-01 09:57:59,57.983333
204534,2023-08-01,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,S05,09:00,Rest,2023-08-01 08:00:00,2023-08-01 17:00:00,2023-08-01 09:58:00,2023-08-01 09:59:59,1.983333
204535,2023-08-01,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,S05,10:00,Moderation Task,2023-08-01 08:00:00,2023-08-01 17:00:00,2023-08-01 10:00:00,2023-08-01 10:30:59,30.983333
204536,2023-08-01,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,S05,10:00,Rest,2023-08-01 08:00:00,2023-08-01 17:00:00,2023-08-01 10:31:00,2023-08-01 10:32:59,1.983333
...,...,...,...,...,...,...,...,...,...,...,...,...
204946,2023-08-27,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,S05,NaN,NaN,2023-08-27 08:00:00,2023-08-27 17:00:00,NaT,NaT,NaN
204947,2023-08-28,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,S07,NaN,NaN,2023-08-28 09:00:00,2023-08-28 18:00:00,NaT,NaT,NaN
204948,2023-08-29,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,S05,NaN,NaN,2023-08-29 08:00:00,2023-08-29 17:00:00,NaT,NaT,NaN
204949,2023-08-30,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,S01,NaN,NaN,2023-08-30 06:00:00,2023-08-30 15:00:00,NaT,NaT,NaN
204950,2023-08-31,NGUYỄN THANH PHI,TRẦN LÊ NGỌC YẾN,yen.tln@trans-cosmos.com.vn,OFF,NaN,NaN,NaT,NaT,NaT,NaT,NaN

In [25]:
keep_values = ['UL', 'AL', 'MC', 'EL', 'MIA', 'HDL', 'AL/2', 'HDL/2', 'H']
keep_values += ['S'+str(i) for i in range(100)]
keep_values += ['S0'+str(i) for i in range(10)]

Shrinkage_Data = Shrinkage_Data[Shrinkage_Data['Shift'].isin(keep_values) | Shrinkage_Data['Shift'].str.match('^P$') | Shrinkage_Data['Shift'].astype(str).str.match('^P\d+$')]
Shrinkage_Data = Shrinkage_Data[~Shrinkage_Data['Shift'].str.startswith('S') | Shrinkage_Data['Shift'].str[1:].astype(str).str.isdigit() | Shrinkage_Data['Shift'].astype(str).str.match('^P\d+$')]

In [26]:
def get_type(shift_value):
    if shift_value in ('MC', 'HDL', 'MIA','HDL/2','EL'):
        return 'Unplanned'
    elif 'S' in shift_value :
        return 'Working Shift'
    elif 'P' in shift_value :
        return 'Newbie Training'
    else:
        return 'Planned'
     
Shrinkage_Data['Type'] = Shrinkage_Data['Shift'].apply(get_type)

In [27]:
Shrinkage_Data['Shift'].unique()

array(['S17', 'S05', 'S01', 'S19', 'HDL', 'UL', 'S11', 'S03', 'S15',
       'S09', 'S13', 'S07', 'AL/2', 'AL', 'MC', 'S29', 'S33', 'S31',
       'MIA', 'P', 'P4'], dtype=object)

In [28]:
Shrinkage_Data['Online'] = Shrinkage_Data['Shift'].apply(lambda x: 0.5 if x in ['HDL', 'AL/2'] else (1 if (type(x) == str) and (x[:2] in ['S0', 'S'] or x[:1] == 'S' ) else 0))
Shrinkage_Data['Headcount'] = Shrinkage_Data['Shift'].apply(lambda x: 0.5 if x in ['HDL', 'AL/2'] else 1)
Shrinkage_Data['Unplanned'] = Shrinkage_Data['Shift'].apply(lambda x: 1 if x in ('MC', 'MIA', 'EL') else 0.5 if x == 'HDL' else 0)
Shrinkage_Data['Planned'] = Shrinkage_Data['Shift'].apply(lambda x: 1 if x in ('AL', 'UL') else 0.5 if x == 'AL/2' else 0)
Shrinkage_Data['newbie_Training'] = Shrinkage_Data['Shift'].apply(lambda x: 1 if re.match('^P(\d+)?$', str(x)) else 0)

Shrinkage_Data = Shrinkage_Data[Shrinkage_Data['Shift'].isin(keep_values) | Shrinkage_Data['Shift'].astype(str).str.match('^S(\d{1,})') | Shrinkage_Data['Shift'].astype(str).str.match('^P(\d{1,})$') | Shrinkage_Data['Shift'].astype(str).str.match('^P$')]

In [29]:
Shrinkage_Data['Shift'].unique()

array(['S17', 'S05', 'S01', 'S19', 'HDL', 'UL', 'S11', 'S03', 'S15',
       'S09', 'S13', 'S07', 'AL/2', 'AL', 'MC', 'S29', 'S33', 'S31',
       'MIA', 'P', 'P4'], dtype=object)

In [30]:
df_unplanned = Shrinkage_Data[Shrinkage_Data['Type'] == 'Unplanned']
df_planned = Shrinkage_Data[Shrinkage_Data['Type'] == 'Planned']
df_newbie_training = Shrinkage_Data[Shrinkage_Data['Type'] == 'newbie_Training']

In [31]:
# Gom nhóm theo 'Month', 'Date' và đếm số lượng
headcount_total = Shrinkage_Data.groupby(['Month','Date'])['Shift'].count().reset_index().rename(columns={'Shift':'Total'})
headcount_online = Shrinkage_Data.groupby(['Month','Date'])['Online'].sum().reset_index()
headcount_unplanned = df_unplanned.groupby(['Month','Date'])['Type'].count().reset_index().rename(columns={'Type':'Unplanned'})
headcount_planned = df_planned.groupby(['Month','Date'])['Type'].count().reset_index().rename(columns={'Type':'Planned'})
headcount_newbie_training = df_newbie_training.groupby(['Month','Date'])['Type'].count().reset_index().rename(columns={'Type':'Planned'})

In [32]:
headcount = headcount_total.merge(headcount_online, on=['Month', 'Date']).merge(headcount_unplanned, on=['Month', 'Date']).merge(headcount_planned, on=['Month', 'Date'])

In [33]:
headcount

     Month       Date  Total  Online  Unplanned  Planned
0   August 2023-08-01    446   418.0         12       22
1   August 2023-08-02    438   413.0          8       20
2   August 2023-08-03    437   414.5         12       15
3   August 2023-08-04    429   399.5         14       23
4   August 2023-08-05    420   391.5         12       21
5   August 2023-08-06    350   319.5         10       25
6   August 2023-08-07    452   402.5          7       20
7   August 2023-08-08    459   414.5          7       15
8   August 2023-08-09    462   413.0         14       18
9   August 2023-08-10    455   404.0         10       20
10  August 2023-08-11    450   394.5          7       26
11  August 2023-08-12    450   386.0         10       33
12  August 2023-08-13    354   317.0         11       31
13  August 2023-08-14    458   392.0          5       38
14  August 2023-08-15    462   407.0          6       28
15  August 2023-08-16    462   405.5          8       27
16  August 2023-08-17    460   403.5         10       27
17  August 2023-08-18    455   396.5         14       26
18  August 2023-08-19    454   382.0         18       40
19  August 2023-08-20    357   327.5          8       25
20  August 2023-08-21    480   420.5          8       29
21  August 2023-08-22    482   417.0          9       37
22  August 2023-08-23    478   415.0          6       35
23  August 2023-08-24    477   425.0         10       21
24  August 2023-08-25    473   427.5          9       40
25  August 2023-08-26    432   405.5         13       19
26  August 2023-08-27    356   330.0          7       22
27  August 2023-08-28    430   421.5          3        6
28  August 2023-08-29    431   422.0          3        6
29  August 2023-08-30    429   419.0          3        7
30  August 2023-08-31    424   416.0          3        5

In [34]:
Shrinkage_Data['Shift'].unique()

array(['S17', 'S05', 'S01', 'S19', 'HDL', 'UL', 'S11', 'S03', 'S15',
       'S09', 'S13', 'S07', 'AL/2', 'AL', 'MC', 'S29', 'S33', 'S31',
       'MIA', 'P', 'P4'], dtype=object)

In [35]:
Shrinkage_Data = Shrinkage_Data.reset_index(drop=True)

In [36]:
unique_shifts = Shrinkage_Data.groupby('Shift').first().reset_index()
unique_shifts[['Shift','Type']]

   Shift             Type
0     AL          Planned
1   AL/2          Planned
2    HDL        Unplanned
3     MC        Unplanned
4    MIA        Unplanned
5      P  Newbie Training
6     P4  Newbie Training
7    S01    Working Shift
8    S03    Working Shift
9    S05    Working Shift
10   S07    Working Shift
11   S09    Working Shift
12   S11    Working Shift
13   S13    Working Shift
14   S15    Working Shift
15   S17    Working Shift
16   S19    Working Shift
17   S29    Working Shift
18   S31    Working Shift
19   S33    Working Shift
20    UL          Planned

In [37]:
Shrinkage_Data['Shift'].unique()

array(['S17', 'S05', 'S01', 'S19', 'HDL', 'UL', 'S11', 'S03', 'S15',
       'S09', 'S13', 'S07', 'AL/2', 'AL', 'MC', 'S29', 'S33', 'S31',
       'MIA', 'P', 'P4'], dtype=object)

In [38]:
all_sheets_shrinkage = {'Shrinkage_all_mods':headcount,
                      'Shrinkage_all_days': Shrinkage_Data}

In [39]:
Shrinkage_writer = pd.ExcelWriter('C:/Users/v6210227/Desktop/shrinkage analysis.xlsx', engine='xlsxwriter')

for sheet_name in all_sheets_shrinkage.keys():
    all_sheets_shrinkage[sheet_name].to_excel(Shrinkage_writer, sheet_name=sheet_name, index=True)

Shrinkage_writer.close()

In [ ]:
# Shrinkage_Data.to_excel("D:/Export temp/Shrinkage temp.xlsx")